/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.grupo12.view;

import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import pe.grupo12.modelo.Publicacion;
import pe.grupo12.modelo.TipoPublicacion;
import pe.grupo12.services.impl.PublicacionServiceImpl;
import pe.grupo12.services.impl.TipoPublicacionServiceImpl;

/**
 *
 * @author HP
 */
public class RegPublicacionView extends javax.swing.JInternalFrame {
    List<String> tiposPublicacion = new ArrayList<>();
    List<TipoPublicacion> tipos = new ArrayList<>();
    
    TipoPublicacionServiceImpl tipoPublicacionService;
    PublicacionServiceImpl publicacionService;
    
    DefaultTableModel model;

    /**
     * Creates new form RegPublicacionView
     */
    public RegPublicacionView() {
        initComponents();
        tipoPublicacionService = new TipoPublicacionServiceImpl();
        publicacionService = new PublicacionServiceImpl();
        
        tipos = tipoPublicacionService.litarTipos();
        tiposPublicacion = tipos.stream().map(TipoPublicacion::getId).collect(Collectors.toList());
        tiposPublicacion.forEach(item -> cbx_IdTipo.addItem(item));
        
        model = (DefaultTableModel) tblReporteNuevaPublicacion.getModel();
        
        cbx_IdTipo.addItemListener(this::cbxTipoPublicacionItemStateChanged);
        cbx_IdTipo.setSelectedIndex(-1);
        
        txtNroEdicion.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                validarDigitos(e);
                
                if (txtNroEdicion.getText().length() >= 3 )
                    e.consume();
            }
        });
        
        txtPrecio.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                validarDigitos(e);
            }
        });
        
        txtStock.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                validarDigitos(e);
            }
        });
    }
    
    public void validarDigitos(KeyEvent e) {
        char c = e.getKeyChar();
        
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            e.consume();
        }
    }
    
    // Evento de selección de tipos de publicación
    public void cbxTipoPublicacionItemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
            generarIdPublicacion();
        }
    }
    
    private void generarIdPublicacion() {
        String idTipo = cbx_IdTipo.getSelectedItem().toString();
        tipos = tipoPublicacionService.litarTipos();
        Optional<TipoPublicacion> tipoOptional = tipos.stream().filter(item -> item.getId().equals(idTipo)).findFirst();

        if (tipoOptional.isPresent()) {
            TipoPublicacion tipo = tipoOptional.get();
            int contador = tipo.getContador() + 1;
            String idPublicacion = String.format("%" + (-(contador > 9 ? 6 : 7)) + "s", tipo.getId());
            idPublicacion = idPublicacion.replace(" ", "0");
            idPublicacion = String.format("%s%s", idPublicacion, contador);
            txtIdPublicacion.setText(idPublicacion);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpnNuevaPublicacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbx_IdTipo = new javax.swing.JComboBox<>();
        txtIdPublicacion = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtNroEdicion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jpnResultadoNuevaPublicacion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporteNuevaPublicacion = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("REGISTRAR NUEVA PUBLICACIÓN");

        jpnNuevaPublicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CRITERIO N.P.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel1.setText("ID TIPO:");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel2.setText("ID PUBLICACIÓN:");

        btnSalir.setBackground(new java.awt.Color(0, 102, 204));
        btnSalir.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevo.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 102, 204));
        btnGuardar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 204));
        btnCancelar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel3.setText("TÍTULO:");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel4.setText("AUTOR:");

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel5.setText("NRO. EDICIÓN:");

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel6.setText("PRECIO:");

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel7.setText("STOCK:");

        cbx_IdTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_IdTipoItemStateChanged(evt);
            }
        });
        cbx_IdTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_IdTipoActionPerformed(evt);
            }
        });

        txtIdPublicacion.setEditable(false);
        txtIdPublicacion.setEnabled(false);
        txtIdPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPublicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnNuevaPublicacionLayout = new javax.swing.GroupLayout(jpnNuevaPublicacion);
        jpnNuevaPublicacion.setLayout(jpnNuevaPublicacionLayout);
        jpnNuevaPublicacionLayout.setHorizontalGroup(
            jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_IdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNroEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                        .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnNuevaPublicacionLayout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnNuevaPublicacionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnNuevaPublicacionLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnNuevaPublicacionLayout.setVerticalGroup(
            jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNuevaPublicacionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbx_IdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtNroEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jpnNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpnResultadoNuevaPublicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO N.P.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        tblReporteNuevaPublicacion.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        tblReporteNuevaPublicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PUBLICACIÓN", "TÍTULO", "ID TIPO", "AUTOR", "NRO EDICIÓN", "PRECIO", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReporteNuevaPublicacion);
        if (tblReporteNuevaPublicacion.getColumnModel().getColumnCount() > 0) {
            tblReporteNuevaPublicacion.getColumnModel().getColumn(0).setResizable(false);
            tblReporteNuevaPublicacion.getColumnModel().getColumn(1).setResizable(false);
            tblReporteNuevaPublicacion.getColumnModel().getColumn(2).setResizable(false);
            tblReporteNuevaPublicacion.getColumnModel().getColumn(3).setResizable(false);
            tblReporteNuevaPublicacion.getColumnModel().getColumn(4).setResizable(false);
            tblReporteNuevaPublicacion.getColumnModel().getColumn(5).setResizable(false);
            tblReporteNuevaPublicacion.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jpnResultadoNuevaPublicacionLayout = new javax.swing.GroupLayout(jpnResultadoNuevaPublicacion);
        jpnResultadoNuevaPublicacion.setLayout(jpnResultadoNuevaPublicacionLayout);
        jpnResultadoNuevaPublicacionLayout.setHorizontalGroup(
            jpnResultadoNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnResultadoNuevaPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jpnResultadoNuevaPublicacionLayout.setVerticalGroup(
            jpnResultadoNuevaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnResultadoNuevaPublicacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnNuevaPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnResultadoNuevaPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnNuevaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnResultadoNuevaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        cbx_IdTipo.setSelectedIndex(-1);
        limpiarFormulario();
        txtIdPublicacion.setText("");
        model.setRowCount(0);
        model.fireTableDataChanged();
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Publicacion publicacion = new Publicacion();
        publicacion.setId(txtIdPublicacion.getText());
        publicacion.setTitulo(txtTitulo.getText());
        publicacion.setIdTipo(cbx_IdTipo.getSelectedItem().toString());
        publicacion.setAutor(txtAutor.getText());
        publicacion.setNroEdicion(Integer.parseInt(txtNroEdicion.getText()));
        publicacion.setPrecio(Float.parseFloat(txtPrecio.getText()));
        publicacion.setStock(Integer.parseInt(txtStock.getText()));
        
        publicacion = publicacionService.agregar(publicacion);
        limpiarFormulario();
        generarIdPublicacion();
        
        model.addRow(new Object[] {
            publicacion.getId(),
            publicacion.getTitulo(),
            publicacion.getIdTipo(),
            publicacion.getAutor(),
            publicacion.getNroEdicion(),
            publicacion.getPrecio(),
            publicacion.getStock()
        });
        
        tblReporteNuevaPublicacion.setModel(model);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbx_IdTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_IdTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_IdTipoActionPerformed

    private void cbx_IdTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_IdTipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_IdTipoItemStateChanged

    private void txtIdPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPublicacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbx_IdTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpnNuevaPublicacion;
    private javax.swing.JPanel jpnResultadoNuevaPublicacion;
    private javax.swing.JTable tblReporteNuevaPublicacion;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtIdPublicacion;
    private javax.swing.JTextField txtNroEdicion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    public void limpiarFormulario() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtNroEdicion.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
    }
}
