/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.grupo12.view;

import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.grupo12.modelo.Publicacion;
import pe.grupo12.modelo.TipoPublicacion;
import pe.grupo12.modelo.Usuario;
import pe.grupo12.modelo.Venta;
import pe.grupo12.services.impl.PublicacionServiceImpl;
import pe.grupo12.services.impl.TipoPublicacionServiceImpl;
import pe.grupo12.services.impl.VentaServiceImpl;

/**
 *
 * @author HP
 */
public class RegVentasView extends javax.swing.JInternalFrame {
    private Usuario usuario;
    List<String> tiposPublicacion = new ArrayList<>();
    List<Publicacion> publicaciones = new ArrayList<>();
    Publicacion publicacionSeleccionada = null;
    Venta venta = new Venta();
    
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    DefaultTableModel model;
    
    TipoPublicacionServiceImpl tipoPublicacionService;
    PublicacionServiceImpl publicacionService;
    VentaServiceImpl ventaService;

    /**
     * Creates new form RegVentasView
     */
    public RegVentasView() {
        initComponents();
        tipoPublicacionService = new TipoPublicacionServiceImpl();
        publicacionService = new PublicacionServiceImpl();
        ventaService = new VentaServiceImpl();
        
        List<TipoPublicacion> tipos = tipoPublicacionService.litarTipos();
        tiposPublicacion = tipos.stream().map(TipoPublicacion::getId).collect(Collectors.toList());
        tiposPublicacion.forEach(item -> cbxTipoPublicacion.addItem(item));
        
        cbxTipoPublicacion.addItemListener(this::cbxTipoPublicacionItemStateChanged);
        setCbxPublicacionItems(tiposPublicacion.get(0));
        
        cbxPublicacion.addItemListener(this::cbxPublicacionItemStateChanged);
        
        txtCantidad.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
            }
        });
        
        txtIdEmpleado.setText("3");
        
        txtFechaVenta.setText(format.format(new Date()));
        model = (DefaultTableModel) tblReporteRegistroDeVentas.getModel();
        // MainView main = (MainView) this.getParent();
        // txtIdEmpleado.setText(main.getUsuario().getId().toString());
    }
    
    // Evento de selección de tipos de publicación
    public void cbxTipoPublicacionItemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
            setCbxPublicacionItems(e.getItem().toString());
        }
    }
    
    // Evento de selección de publicación
    public void cbxPublicacionItemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
            setStockValue();
        }
    }
    
    private void setCbxPublicacionItems(String tipo) {
        cbxPublicacion.removeAllItems();
        publicaciones = publicacionService.listarPorTipo(tipo);
        publicaciones.forEach(item -> cbxPublicacion.addItem(String.format("%s - %s", item.getId(), item.getTitulo())));
        setStockValue();
    }
    
    private void setStockValue() {
        String[] valores = cbxPublicacion.getSelectedItem().toString().split("-");
        Optional<Publicacion> seleccionOptional = publicaciones.stream().filter(item -> item.getId().equals(valores[0].trim())).findAny();
            
        if (seleccionOptional.isPresent()) {
            publicacionSeleccionada = seleccionOptional.get();
            txtStock.setText(String.valueOf(publicacionSeleccionada.getStock()));
            txtPrecio.setText(String.valueOf(publicacionSeleccionada.getPrecio()));
            calcularMontos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRegistroDeVentas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtIdVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtFechaVenta = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxTipoPublicacion = new javax.swing.JComboBox<>();
        cbxPublicacion = new javax.swing.JComboBox<>();
        jpnResultadoRegistroDeVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporteRegistroDeVentas = new javax.swing.JTable();

        setTitle("REGISTRO DE VENTAS");

        jpnRegistroDeVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CRITERIO R.V.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel1.setText("ID VENTA:");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel2.setText("CLIENTE:");

        btnSalir.setBackground(new java.awt.Color(0, 102, 204));
        btnSalir.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevo.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 102, 204));
        btnGuardar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 204));
        btnCancelar.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel3.setText("FECHA VENTA:");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel4.setText("EMPLEADO:");

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel5.setText("TIPO PUB:");

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel6.setText("CANTIDAD:");

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel7.setText("PRECIO UNIT:");

        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCantidadMouseExited(evt);
            }
        });
        txtCantidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCantidadPropertyChange(evt);
            }
        });

        txtIdVenta.setEnabled(false);
        txtIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVentaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel8.setText("STOCK:");

        txtStock.setEditable(false);
        txtStock.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel9.setText("DESCUENTO:");

        txtDescuento.setEditable(false);
        txtDescuento.setEnabled(false);
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel10.setText("SUB-TOTAL:");

        txtSubTotal.setEditable(false);
        txtSubTotal.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel11.setText("IMPUESTO:");

        txtImpuesto.setEditable(false);
        txtImpuesto.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel12.setText("TOTAL:");

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);

        txtFechaVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel13.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel13.setText("PUBLICACIÓN:");

        javax.swing.GroupLayout jpnRegistroDeVentasLayout = new javax.swing.GroupLayout(jpnRegistroDeVentas);
        jpnRegistroDeVentas.setLayout(jpnRegistroDeVentasLayout);
        jpnRegistroDeVentasLayout.setHorizontalGroup(
            jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                        .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(txtFechaVenta)
                                    .addComponent(cbxTipoPublicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStock))))
                        .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                                        .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(42, 42, 42)
                                        .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdEmpleado)
                                            .addComponent(txtCliente)))
                                    .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                                        .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addGap(51, 51, 51)
                                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbxPublicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jpnRegistroDeVentasLayout.setVerticalGroup(
            jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistroDeVentasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(cbxTipoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jpnRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpnResultadoRegistroDeVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO R.V.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Console", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        tblReporteRegistroDeVentas.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        tblReporteRegistroDeVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VENTA ", "CLIENTE", "FECHA", "ID EMPLEADO", "ID PUBLICACIÓN", "CANTIDAD", "PRECIO", "DSCTO", "SUB-TOTAL", "IMPUESTO", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReporteRegistroDeVentas);
        if (tblReporteRegistroDeVentas.getColumnModel().getColumnCount() > 0) {
            tblReporteRegistroDeVentas.getColumnModel().getColumn(0).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(1).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(2).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(3).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(4).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(5).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(6).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(7).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(8).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(9).setResizable(false);
            tblReporteRegistroDeVentas.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout jpnResultadoRegistroDeVentasLayout = new javax.swing.GroupLayout(jpnResultadoRegistroDeVentas);
        jpnResultadoRegistroDeVentas.setLayout(jpnResultadoRegistroDeVentasLayout);
        jpnResultadoRegistroDeVentasLayout.setHorizontalGroup(
            jpnResultadoRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnResultadoRegistroDeVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jpnResultadoRegistroDeVentasLayout.setVerticalGroup(
            jpnResultadoRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnResultadoRegistroDeVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRegistroDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpnResultadoRegistroDeVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnRegistroDeVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpnResultadoRegistroDeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.limpiarFormulario();
        model.setRowCount(0);
        model.fireTableDataChanged();
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:        
        venta.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
        venta.setCliente(txtCliente.getText());
        
        try {
            venta.setFecha(format.parse(txtFechaVenta.getText()));
        } catch (ParseException e) {
            venta.setFecha(new Date());
        }
        
        venta.setIdPublicacion(publicacionSeleccionada.getId());
        
        Venta ventaBD = ventaService.registrarVenta(venta);
        limpiarFormulario();
        
        model.addRow(new Object[]{
            ventaBD.getId(),
            ventaBD.getCliente(),
            format.format(ventaBD.getFecha()),
            ventaBD.getIdEmpleado(),
            ventaBD.getIdPublicacion(),
            ventaBD.getCantidad(),
            ventaBD.getPrecio(),
            ventaBD.getDcto(),
            ventaBD.getSubTotal(),
            ventaBD.getImpuesto(),
            ventaBD.getTotal()
        });
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVentaActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        // TODO add your handling code here:
        calcularMontos();
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtCantidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCantidadPropertyChange
        // TODO add your handling code here:
        // calcularMontos();
    }//GEN-LAST:event_txtCantidadPropertyChange

    private void txtCantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseExited
        // TODO add your handling code here:
        // calcularMontos();
    }//GEN-LAST:event_txtCantidadMouseExited

    private void calcularMontos() {
        if (txtCantidad.getText().length() > 0) {
            // Validar cantidad contra el stock
            int stock = publicacionSeleccionada.getStock();
            int cantidad = Integer.parseInt(txtCantidad.getText());

            if (cantidad <= stock) {
                venta.setCantidad(cantidad);
                venta.setPrecio(Float.parseFloat(txtPrecio.getText()));

                // Obtener totales
                Venta ventaDescuentos = ventaService.calcularMontos(venta);
                venta.setDcto(ventaDescuentos.getDcto());
                venta.setSubTotal(ventaDescuentos.getSubTotal());
                venta.setImpuesto(ventaDescuentos.getImpuesto());
                venta.setTotal(ventaDescuentos.getTotal());

                txtDescuento.setText(String.format("%.2f", venta.getDcto()));
                txtSubTotal.setText(String.format("%.2f", venta.getSubTotal()));
                txtImpuesto.setText(String.format("%.2f", venta.getImpuesto()));
                txtTotal.setText(String.format("%.2f", venta.getTotal()));

                btnGuardar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "No hay stock suficiente");
                btnGuardar.setEnabled(false);
            }
        }
    }
    
    private void limpiarFormulario() {
        txtCliente.setText("");
        cbxTipoPublicacion.setSelectedIndex(0);
        cbxPublicacion.setSelectedIndex(0);
        txtFechaVenta.setText(format.format(new Date()));
        txtCantidad.setText("");
        txtDescuento.setText("");
        txtSubTotal.setText("");
        txtImpuesto.setText("");
        txtTotal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxPublicacion;
    private javax.swing.JComboBox<String> cbxTipoPublicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnRegistroDeVentas;
    private javax.swing.JPanel jpnResultadoRegistroDeVentas;
    private javax.swing.JTable tblReporteRegistroDeVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JFormattedTextField txtFechaVenta;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtImpuesto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}
